language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: 
        - g++-9

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -qq g++-6
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
#- sudo apt-get install libboost-all-dev
 - cd "${TRAVIS_BUILD_DIR}"
 - g++ --version

script:
 - mkdir build
 - cd build
 - cmake ..
 - make HeapTest
 - ./HeapTest
