language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-9, valgrind]

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev valgrind cmake
 - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
 - sudo tar xf release-1.7.0.tar.gz
 - cd googletest-release-1.7.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - which valgrind
 - tar -xzf boost_1_64_0.tar.gz
 - ./b2 -d0
 - ./b2 install -d0
 - cd "${TRAVIS_BUILD_DIR}"
 - g++ --version
 - g++-9 --version
 - alias g++="g++-9"
 - g++ --version

script:
 - g++ --version
 - g++-9 --version
 - g++ --version
 - make runtests
