language: cpp
matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - COMPILER=g++-9
    addons:
      apt:
        packages: 
        - libboost-all-dev
        - g++-9

script:
 - make h8.o
 - mkdir build
 - cd build
 - cmake ..
 - make HeapTest
 - ./HeapTest
