language: cpp
matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - COMPILER=g++-9
    addons:
      apt:
         sources: 
          - ubuntu-toolchain-r-test
      packages:
        - libboost-all-dev
        - g++-9

script:
 - mkdir build
 - cd build
 - cmake ..
 - make HeapTest
 - ./HeapTest
