language: cpp
matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        packages:
        - libboost-all-dev
script:
 - mkdir build
 - cd build
 - cmake ..
 - make runtests
