language: cpp
matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        packages:
        - libboost-all-dev
        - libgflags-dev
        - libevent-dev
        - libdouble-conversion-dev
        - libgoogle-glog-dev
        - libiberty-dev
        - liblz4-dev
        - liblzma-dev
        - libsnappy-dev
        - zlib1g-dev
        - binutils-dev
        - libjemalloc-dev
        - libssl-dev
        - pkg-config
        - libunwind-dev
        - libfmt-dev
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Debug ..
 - make runtests
 - make clean
 - cmake -DCMAKE_BUILD_TYPE=Release ..
 - make runbenchmarks
