language: cpp
matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        packages:
        - libboost-all-dev
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Debug ..
 - make VERBOSE=1 runtests
 - cmake -DCMAKE_BUILD_TYPE=Release ..
 - make VERBOSE=1 runbenchmarks
